In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [16]:
arr=[[5, 2, 3],
     [4, 5, 6],
     [7, 587, 9]]

print(np.linalg.det(arr))
print(np.linalg.inv(arr))

-10433.999999999996
[[ 3.33237493e-01 -1.67050029e-01  2.87521564e-04]
 [-5.75043128e-04 -2.30017251e-03  1.72512938e-03]
 [-2.21679126e-01  2.79950163e-01 -1.62928886e-03]]


In [21]:
arr=[[15, 29],
     [34, 58],
     [13, 21]]

print(np.linalg.pinv(arr))
print(arr @ np.linalg.pinv(arr) @ arr)

[[-0.42486772  0.13354497  0.2178836 ]
 [ 0.25132275 -0.06455026 -0.12116402]]
[[15. 29.]
 [34. 58.]
 [13. 21.]]


In [8]:
arr=[[5]]

print(np.linalg.inv(arr))

[[0.2]]
